export const categories = [
  {
    iconClass: "Category-icon Category-text-secondVariant",
    textClass: "Category-text Category-text-secondVariant",
    text: "Nudelvorsatz 3-tlg Set 5KSMPRA",
    alt: "Nudelvorsatz 3-tlg Set 5KSMPRA",
    width: 160,
    height: 202,
    src: "/category-1.png",
  },
  {
    iconClass: "Category-icon Category-text-secondVariant",
    textClass: "Category-text Category-text-secondVariant",
    text: "Gemüseschneider 5KSMVSA",
    alt: "Gemüseschneider 5KSMVSA",
    width: 160,
    height: 202,
    src: "/category-2.png",
  },
  {
    iconClass: "Category-icon Category-text-secondVariant",
    textClass: "Category-text Category-text-secondVariant",
    text: "Food-Processor-Vorsatz 5KSM2FPA",
    alt: "Food-Processor-Vorsatz 5KSM2FPA",
    width: 160,
    height: 202,
    src: "/category-3.png",
  },
  {
    iconClass: "Category-icon Category-text-secondVariant",
    textClass: "Category-text Category-text-secondVariant",
    text: "Ganzmetall-Fleischwolf 5KSMMGA",
    alt: "Ganzmetall-Fleischwolf 5KSMMGA",
    width: 160,
    height: 202,
    src: "/category-4.png",
  },
];

export const secondcategories = [
  {
    iconClass: "Category-icon Category-text-firstVariant",
    textClass: "Category-text Category-text-firstVariant",
    text: "Jetzt entdecken",
    alt: "Jetzt entdecken",
    width: 160,
    height: 202,
    src: "/secondcategory-1.png",
  },
  {
    iconClass: "Category-icon Category-text-firstVariant",
    textClass: "Category-text Category-text-firstVariant",
    text: "Jetzt entdecken",
    alt: "Jetzt entdecken",
    width: 160,
    height: 202,
    src: "/secondcategory-2.png",
  },
  {
    iconClass: "Category-icon Category-text-firstVariant",
    textClass: "Category-text Category-text-firstVariant",
    text: "Jetzt entdecken",
    alt: "Jetzt entdeckenr",
    width: 160,
    height: 202,
    src: "/secondcategory-3.png",
  },
  {
    iconClass: "Category-icon Category-text-firstVariant",
    textClass: "Category-text Category-text-firstVariant",
    text: "Summer Sale",
    alt: "Summer Sale",
    width: 160,
    height: 202,
    src: "/secondcategory-4.png",
  },
];
