import Header from "@/components/Header";
import Offer from "@/components/Offer";

import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sergent Major</title>
        <meta name="description" content="Generated by SMBS Solutions" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header
          logoHeight={52}
          logoWidth={104}
          title="Weihnachten mit KitchenAid"
          imgCover="Header-cover"
          imgArrow="Arrow-img"
          paragraph="Entdecke dein exklusives Angebot"
        />
        <Offer title="EXKLUSIV FÜR VEEPEE-MITGLIEDER" />
      </main>
    </>
  );
}
