import Benefits from "@/components/Benefits";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Offer from "@/components/Offer";
import Preferences from "@/components/Preferences";
import Products from "@/components/Products";
import Selections from "@/components/Selections";

import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>GROHE</title>
        <meta name="description" content="Generated by SMBS Solutions" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header
          logoSrc="/header-logo.png"
          logoAlt="header-logo"
          logoWidth={78}
          logoHeight={52}
        />
        <div className="OfferProductsImg">
          <Offer />
          <Products />
        </div>
        <Benefits />
        <Preferences />
        <Selections />
        <Footer
          text="© GROHE 2023. Tutti i diritti riservati."
          src="/footer-logo.png"
          alt="hooter-image"
          height={52}
          width={227}
        />
      </main>
    </>
  );
}
