import Benefits from "@/components/Benefits";
import Header from "@/components/Header";
import Offer from "@/components/Offer";
import Products from "@/components/Products";

import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>GROHE</title>
        <meta name="description" content="Generated by SMBS Solutions" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header
          logoSrc="/header-logo.png"
          logoAlt="header-logo"
          logoWidth={78}
          logoHeight={52}
        />
        <Offer />
        <Products />
        <Benefits />
      </main>
    </>
  );
}
